version: '3.4'

services:
  parcelfrontend:
    image: parcelfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
